### PR TITLE
Fixes some issues with the generator

### LINKED ISSUE #17: Failure message on fresh install and rspec run.
rails new APP_NAME
 - added gem 'stitches'
rails g rspec:install
rails g apitome:install
rails g stitches:api
 - create database
 - run migrations
 - run rspec to validate setup

[error]
uninitialized constant RSpec::Rails (NameError)

### PR DESCRIPTION
**Pull request by davetron5000**
- putting stuff in spec_helper that should be in rails_helper
- not requiring some gems when needed
- referencing spec_helper instead of rails_helper
- not including capybara (not sure why this isn't brought in by rspec_api_documentation)

We need a better test of the generator.  It's tricky, but we basically need a test that:

1. `rails new blah`
1. Add `stitches` to the `Gemfile`
1. Run rspec and stitches generators
1. configure a database
1. Run the specs of the generated rails app

Tests like this are hard to keep from being brittle.  Any thoughts on if I should try to do that before merging this?

Fixes #17

### CODE REVIEW

File: lib/stitches/api_generator.rb [hunk 1]
```diff
@@ -62,16 +63,17 @@ def bootstrap_api
       sleep 1 # allow clock to tick so we get different numbers
       migration_template "db/migrate/create_api_clients.rb", "db/migrate/create_api_clients.rb"
 
-      inject_into_file 'spec/spec_helper.rb', %q{
+      inject_into_file 'spec/rails_helper.rb', %q{
```
Comment (davetron5000) [inline lib/stitches/api_generator.rb]: So many of our internal apps were migrated from RSpec 2 and from a config that just has everything in `spec_helper` :(

**Comment by davetron5000** [comment]
#22 captures the need to write a test
